### ISSUE TITLE
noch mehr Fehler in Move#perform!(gamestate) ⇒ Object 

### ISSUE THREAD

**Issue by kwollw** [CAU-Kiel-Tech-Inf/socha-client-ruby#15]
Schaut man sich die Beschreibung und Implementierung dieser Methode genauer an, stellt man einen grundlegenden Fehler fest, der möglicherweise auf unzureichende Kenntnisse in Ruby zurückzuführen ist.

Beabsichtigt ist nach der Kommentierung eine Mutierung des gamestate-Objektes, dass als Parameter übergeben wird. Allerdings wird in Ruby stets eine Kopie des Objektes als Argument übergeben. Also bleibt die Wirkung der Veränderung lokal.

Vielmehr könnte es in gamestate eine Methode perform_move!(move) geben.

```ruby
def perform_move!(move) 
if GameRuleLogic.valid_move?(move, board, current_player_color)
    type = board.field(x, y).type
    board.change_field(x, y, FieldType::EMPTY)
    target = GameRuleLogic.move_target(move, board)
    board.change_field(target.x, target.y, type)
  else
    raise InvalidMoveException.new('Invalid move', move)
  end
  # change the state to the next turn
  last_move = move
  turn += 1
  switch_current_player
end
```

**Comment by kwollw** [comment]
Mit der Angabe zur Parameterübergabe habe ich mich geirrt. Asche auf mein Haupt. Der Fehler muss irgendwo anders liegen.

**Comment by SKoschnicke** [comment]
Durch die Meldung habe ich schonmal einen Fehler in `perfom!` gefunden und behoben (siehe a3e5e8556ea05291b714bfadbb40c5d59e5e02b6). Danke für den Hinweis. Das mit `current_player` schaue ich mir jetzt auch noch an.

**Comment by kwollw** [comment]
Der Fehler liegt in Gamestate#switch_current_player:

```ruby
# Wechselt den Spieler, der aktuell an der Reihe ist.
def switch_current_player
-    current_player_color = other_player_color
+   @current_player_color = other_player_color
end
```

**Comment by SKoschnicke** [comment]
Vielen Dank! Ist alles in Version 19.0.4 behoben.
