### ISSUE TITLE
Spielende wird nicht behandelt

### ISSUE THREAD

**Issue by kwollw** [CAU-Kiel-Tech-Inf/socha-client-ruby#16]
Veränderungen eines Gamestate-Objektes (z. B. durch Move#perform!) werden nicht gestestet auf Erreichen des Spielendes. Insofern bleibt Gamestate#condition immer nil und die Funktion game_over? kann nicht verwendet werden. Dies kann durch Änderung von Gamestate#game_ended? behoben werden.

```ruby
def game_ended?
    if condition.nil?
      current_players_swarm_size = GameRuleLogic.swarm_size(board, current_player_color)
      current_players_fields_count = board.fields_of_type(PlayerColor.field_type(current_player_color)).size
      other_players_swarm_size = GameRuleLogic.swarm_size(board, other_player_color)
      other_players_fields_count = board.fields_of_type(PlayerColor.field_type(other_player_color)).size
      #check for game ended condition
      if turn == 60 ||current_players_swarm_size == current_players_fields_count || other_players_swarm_size == other_players_fields_count
        if (current_players_swarm_size == current_players_fields_count) ^ (other_players_swarm_size == other_players_fields_count)
          if current_players_swarm_size == current_players_fields_count
            @condition = Condition.new(current_player)
          else
            @condition = Condition.new(other_player)
          end
        else
          if current_players_swarm_size > other_players_swarm_size
            @condition = Condition.new(current_player)
          elsif current_players_swarm_size < other_players_swarm_size
            @condition = Condition.new(other_player)
          else
            @condition = Condition.new(nil)
          end
        end
      end
    end
    !condition.nil?
  end
```

**Comment by SKoschnicke** [comment]
`GameState#condition` wird in einem echten Spiel vom Server gesetzt und `GameState#game_ended?` sollte dann wie vorgesehen funktionieren.

Das nuetzt natuerlich nichts, wenn der Client Strategien durchrechnen will, daher werde ich eine entsprechende Funktion in `GameRuleLogic` implementieren, mit der man die `Condition` fuer einen gegebenen `GameState` berechnen kann.

**Comment by kwollw** [comment]
Genau, meiner Mannschaft ging es darum, im Zuge einer alpha-beta-Suche Gamestate#game_ended aufrufen zu können. Die o. a. Implementation verzögert allerdings die Funktion erheblich, sodass die alpha-beta-Suche recht langsam wird. Zeitkritisch scheint mir die Funktion GameRuleLogic#greatest_swarm_from_fields zu sein. Eventuell könnte eine Funktion GameRuleLogic#any_swarm_from_fields sein, die abbricht, sobald ein vollständiger Schwarm beliebiger Größe ermittelt wurde.

Jeder Gamestate sollte nach Aufruf permutierender Methoden eine Condition erhalten, sofern durch diese Mutation ein Spielende erreicht wurde. Sonst erhalten wir inkonsistente Gamestates, bei denen eine Spielende-Situation eingetreten ist, die Methode Gamestate#game_endet aber nil zurückliefert.

Falls eine Funktion in GameRuleLogic eine Condition berechnen kann, muss diese Funktion nach jeder Mutation eines Gamestates aufgerufen und @condition gesetzt werden, um den Gamestate konsistent zu halten.

**Comment by SKoschnicke** [comment]
In Version 19.1.0 setzt `Move#perform!` jetzt auch die `condition` des GameState, falls ein Spieler gewinnt.
