### ISSUE TITLE
Testspiele werden abgebrochen mit Fehler in protocol.rb

### ISSUE THREAD

**Issue by kwollw** [CAU-Kiel-Tech-Inf/socha-client-ruby#17]
[test_5893__32984__177672.log.log](https://github.com/CAU-Kiel-Tech-Inf/socha-client-ruby/files/2850278/test_5893__32984__177672.log.log)

See attached log file

**Comment by SKoschnicke** [comment]
Das war ein Problem im Wettkampfsystem und ist jetzt behoben.
