### ISSUE TITLE
Ruby client für den neuen Wettbewerb fehlt

### ISSUE THREAD

**Issue by Lasse05** [CAU-Kiel-Tech-Inf/socha-client-ruby#21]
Moin , wir benötigen den Ruby client

**Comment by SKoschnicke** [comment]
Ich kuemmere mich diese Woche darum!

**Comment by SKoschnicke** [comment]
Der Client ist fast fertig. Es gibt nur noch einen seltsamen Fehler in der Kommunikation mit dem Spielserver. Sobald ich die Ursache gefunden habe, gibt es eine erste Version des Gems.

**Comment by SKoschnicke** [comment]
Die erste Version ist jetzt verfuegbar.
